services:
  - type: web
    name: cms-django
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn CMS.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: CMS.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
