# Generated by Django 5.1.4 on 2025-01-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('dob', models.DateField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='student_user')),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
