# Generated by Django 5.1.4 on 2025-01-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='student_user')),
                ('address', models.CharField(max_length=30)),
            ],
        ),
    ]
