# Generated by Django 5.1.4 on 2025-01-14 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.staff'),
        ),
    ]
