# Generated by Django 5.1.4 on 2025-01-15 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_attendance_lecturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physics', models.CharField(max_length=30)),
                ('maths', models.CharField(max_length=30)),
                ('computer_science', models.CharField(max_length=30)),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.studentdetails')),
            ],
        ),
    ]
