# Generated by Django 5.1.4 on 2025-01-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='exam_type',
            field=models.CharField(default='quarterly', max_length=30),
        ),
    ]
