# Generated by Django 5.1.4 on 2025-01-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(choices=[('lab_assistant', 'lab_assistant'), ('lecturer', 'lecturer'), ('clerk', 'clerk')], default='clerk', max_length=30),
        ),
    ]
