# Generated by Django 5.1.4 on 2025-01-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_staff_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='computer_science',
            field=models.IntegerField(max_length=30),
        ),
        migrations.AlterField(
            model_name='marks',
            name='maths',
            field=models.IntegerField(max_length=30),
        ),
        migrations.AlterField(
            model_name='marks',
            name='physics',
            field=models.IntegerField(max_length=30),
        ),
    ]
