# Generated by Django 5.1.4 on 2025-01-21 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_assignmentanswers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentanswers',
            name='teacher',
        ),
    ]
